<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid" style="background-color:whitesmoke;">
      <div class="container">
        <div class="navbar-text">
          <div class="pull-left">
            <p style="margin: 0;">
              <a style="text-decoration: none;" href="https://www.facebook.com/toroitservices/" title="Facebook"><i class="icon-rounded icon-32 icon-facebook"></i></a>
              <a style="text-decoration: none;" href="https://www.linkedin.com/company/torosystems" title="LinkedIn"><i class="icon-rounded icon-32 icon-linkedin"></i></a>
              <a style="text-decoration: none;" href="https://twitter.com/ToroSystems" title="Twitter"><i class="icon-rounded icon-32 icon-twitter"></i></a>
            </p>
          </div>
          <div class="pull-right">
            <p style="margin-bottom: 0;">
              <i class="icon-phone icon-white" style="color:#bf0707;"></i>
              <strong>647 274 7678</strong>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <a class="brand logo" href="/index.html" alt="Toro Systems">
        <img src="/assets/img/logo.png" alt="Toro Systems">
      </a>

      <div class="navigation">
        <nav>
          <ul class="nav topnav">
            <li data-nav-item="home">
              <a href="/index.html" alt="Home">Home</a>
            </li>
            <li data-nav-item="about">
              <a href="/about.html" alt="About">About</a>
            </li>
            <li class="dropdown" data-nav-item="services">
              <a href="/services.html" alt="Services">Services</a>
              <ul class="dropdown-menu">
                <li data-nav-item="alarm"><a href="/alarm.html" alt="Alarm Systems">Alarm Systems</a></li>
                <li data-nav-item="surveillance"><a href="/surveillance.html" alt="CCTV Surveillance">CCTV Surveillance</a></li>
                <li data-nav-item="dooraccess"><a href="/dooraccess.html" alt="Access Control Systems">Access Control</a></li>
                <li data-nav-item="accessibility"><a href="/accessibility.html" alt="Barrier-Free Accessibility">Accessibility</a></li>
              </ul>
            </li>
            <li data-nav-item="areas">
              <a href="/areas.html" alt="Areas We Serve">Areas</a>
            </li>
            <li data-nav-item="contact">
              <a href="/contact.html" alt="Contact Us">Contact</a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>